project:
  type: website

website:
  title: "roberthree"
  navbar:
    tools:
      - icon: github
        href: https://github.com/roberthree/roberthree.github.io/
  reader-mode: true
  repo-url: https://github.com/roberthree/roberthree.github.io/
  repo-actions: [edit, source, issue]

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
